# We ignore the analysis/Waveform part of the initial code.

import joblib
import os
from sklearn.svm import SVC
import time
import cv2
import numpy as np
import matplotlib.pyplot as plt
import serial

class Reservoir:
    def __init__(self, capture_period=0.05, num_frames=50, delay=3, region=[[0, 1], [0, 1]], save_path='models'):
        self.region = region
            # this is the rectangular region from which the camera input is not discarded (with [[a,b],[c,d]] meaning a-b along x, and c-d along y)
            # eg. [[0,0.5],[0.5,1]] means the top-left square when the entire camera input is divided into 4
        self.models = [SVC(kernel='linear', probability=True) for _ in range(num_frames)]
            # returns a list of Support Vector Classifier objects, which have loads of cool methods
            # each SVC in the list looks at one of the camera snapshots (ie. each uses a specific amount of non-linearity)
            # >kernel='linear'< means uses a linear boundary to classify (since non-linearity is generated by reservoir)
            # >probability=True< means it allows for probability distribution over classes, rather than just one-hot vector
        self.feed = cv2.VideoCapture(1, cv2.CAP_DSHOW)
            # cv2.VideoCapture() turns on a live video feed from the camera
            # the argument >1< says to get the feed from the 2nd connected webcam (since counting starts at 0)
            # the cv2.CAP_DSHOW is an argument specific to Windows computers, which helps avoid loads of issues
        self.x_width, self.y_width = int(self.feed.get(cv2.CAP_PROP_FRAME_WIDTH)), int(self.feed.get(cv2.CAP_PROP_FRAME_HEIGHT))
            # this gets the height and width of the video feed in pixels
        self.capture_period, self.num_frames, self.delay = capture_period, num_frames, delay
            # capture_period is the time period between consecutive snapshots by the camera
            # num_frames is the number of snapshots for each example
            # delay is the time to wait between examples (not including the time in self.reset, which is there because it takes time to communicate with Arduino [I think])
        self.combined_model = SVC(kernel='linear', probability=True)
            # this is another SVC object but this one uses the data from all num_frames of the captures
        self.save_path = save_path
            # location in which parameters are saved / loaded from (but not including filename)
            # eg. /Users/safwanalbeshti/Downloads/Project/Models

    def background(self, period=5, show=False):
        # takes images of background then averages them
        frames, start_time = [], time.time()
        while time.time() - start_time < period:
            frames.append(self.capture())
                # makes a list, frames, of a bunch of snapshots (in quickfire succession) of the background
        frame_p = [self.image(frame) for frame in frames]
            # this crops each background snapshot that's just been taken
        background_frame = np.mean(np.array(frame_p), axis=0)
            # this converts the 3d array into a 2d array whose values are the averages over all the cropped background screenshots
        if show:
            plt.imshow(background_frame, cmap='gray')
            plt.axis('off')
            plt.show()
        return background_frame

    def capture(self):
        # takes image AND converts to greyscale
        ret, frame = self.feed.read()
            # ret is True (False) if the camera snapshot was (un)successful
            # frame is a 3d array of shape (height,width,3) (where the 3 is for RBG)
        if ret:
            return cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                # this converts the image 3d array, frame, to greyscale (using the formula grey = 0.114⋅B + 0.587⋅G + 0.299⋅R)
                # each pixel is an integer between 0 and 255 inclusive
                # note that this converts the 3d array into a 2d array [of shape (height,width)]
        else:
            print('Camera Error')

    def image(self, frame, show=False):
        # crops image
        frame = frame[int(self.region[1][0] * self.y_width):int(self.region[1][1] * self.y_width),
                      int(self.region[0][0] * self.x_width):int(self.region[0][1] * self.x_width)]
            # this crops each image
        if show:
            # this allows you to see the captured images in greyscale
            plt.imshow(frame, cmap='gray')
            plt.axis('off')
            plt.show()
        return frame
            # this returns the cropped image

    def filter_image(self, frame, background_frame, factor=5, show=False):
        # removes background AND decreases contrast
        frame = np.array(frame) - np.array(background_frame)
            # converts an image's pixels into a numpy array, then subtracts the background from it
        frame = frame / 255
            # normalises the greyness of each pixel so that the range goes from (0,255) to (0,1)
        frame = np.array([[int(255 / (1 + np.exp(-factor * pixel))) for pixel in row] for row in frame])
            # the 255 is because we need the pixels' greyness to be in the range (0,255)
            # this sigmoid function decreases the contrast: it leaves light grey the same, but makes dark grey lighter
                # note that a pixel value of zero is black and a value of 1 is white
        if show:
            plt.imshow(frame, cmap='gray')
            plt.axis('off')
            plt.show()
        return frame

    def encode(self, input):
        # sends a signal to the solenoids to fire
        ser = serial.Serial('COM3', 115200)
            # this opens up a connection with the USB port named COM3
            # the baud rate 115200 is the number of bits per second that can be communicated
        time.sleep(2)
            # once the connection with the USB port is opened, the Arduino resets, so we need to wait 2s for it to boot up (so that it doesn't miss the message)
        inp = ''.join(str(value) for value in input) + '\n'
            # note that input can of course be a string or a list
        ser.write(inp.encode())
            # this converts inp to binary type
            # the in-built encode() function is not to be confused with the self.encode() method
        ser.close()
            # closes the connection with COM3 to prevent issues (eg. it being closed unintentionally by the garbage collector)

    def reset(self):
        # doesn't do anything useful for our solenoid system [I don't think] - it was useful for the rod system
        ser = serial.Serial('COM3', 115200)
        time.sleep(2)
        ser.write('000000000000'.encode())
        ser.close()

    def seperate(self, frames, background, show_filtered=False):
        filtered = [self.filter_image(self.image(frame), background, factor=20, show=show_filtered) for frame in frames]
            # crops each image out of the num_frames images AND removes the background
        reduced = [Maths(array).AvMatrix([20, 20]).flatten() for array in filtered]
            # converts each image into 20x20 pixels AND flattens each image into 1d array
        return np.array(reduced)

    def test(self, samples, Y):
        scores, Yp = np.zeros(len(self.models)), [model.predict(samples[:, n]) for n, model in enumerate(self.models)]
            # initialises a list of scores, >scores<, one for each model
            # predicts the targets for each example using each model, and stores in the 2d array >Yp<
        Yprob = [model.predict_proba(samples[:, n]) for n, model in enumerate(self.models)]
            # predicts the probabilities of each class for each example for each model, and stores in a 3d array >Yprob<
            # >Yprob< has shape (num_frames,num_examples,num_classes)
        for n, model_answers in enumerate(Yp):
            # for each model's predictions
            for a, answer in enumerate(model_answers):
                    # for each answer predicted by that model
                if answer == Y[a]:
                    # check if the answer is right
                    scores[n] += 1
                        # and if it is then give that model 1 point
        combined_predictions = self.combined_model.predict(samples.reshape(samples.shape[0], -1))
            # returns predicted classes of >combined_model<
        combined_accuracy = np.mean(combined_predictions == Y)
            # returns percentage accuracy of >combined_model<
        return Yp, Yprob, scores / len(Y), combined_predictions, combined_accuracy

    def train(self, samples, Y):
        for n, model in enumerate(self.models):
            model.fit(samples[:, n], Y)
                # this takes the n^th snapshot of each example in the dataset and trains the parameters to predict the targets
                # so it updates the parameters in the >model< object
        combined_samples = samples.reshape(samples.shape[0], -1)
            # turns >samples< into a 2d array of shape (num_examples,num_frames*num_pixels_per_frame)
        self.combined_model.fit(combined_samples, Y)
        print('Models have been trained')

    def save_models(self):
        os.makedirs(self.save_path, exist_ok=True)
            # >os.makedirs()< creates a directory with pathname >self.save_path<
            # >exist_ok=True< tells python not to raise an error if the file already exists
        for n, model in enumerate(self.models):
            joblib.dump(model, f'{self.save_path}/model_{n}.pkl')
                # >joblib.dump()< serialises a python object, meaning it converts it into a format that can be saved to disk
        joblib.dump(self.combined_model, f'{self.save_path}/combined_model.pkl')
        print('Models have been saved')

    def load_models(self):
        for n in range(len(self.models)):
            self.models[n] = joblib.load(f'{self.save_path}/model_{n}.pkl')
                # >joblib.load()< deserialises a file, meaning it converts it into a python object
        self.combined_model = joblib.load(f'{self.save_path}/combined_model.pkl')
        print('Models have been loaded')

    def run(self, data, mode, save=False, load=False, show_filtered=False):
        if load:
            self.load_models()
            return

        if data is None:
            return

        inputs, outputs = data
            # don't actually know what the exact format of the data object should be!!!!
        Samples = []
            # this will be an array of examples, with each example containing num_frames (filtered and cropped) snapshots
        background = self.background()
        for i, input in enumerate(inputs):
            input = [int(value) for value in input]
            print(f'Running input {i+1}: ', input)
            Frames = []
                # this will be an array of num_frames snapshots (all for a single example)
            self.encode(input)
                # sends the input signal to the arduino
            capture_time = time.time() + self.delay
                # waits for self.delay before starting the image capturing
            while len(Frames) < self.num_frames:
                # repeats until num_frames snapshots have been taken
                if time.time() - capture_time > self.capture_period:
                    # waits for the period between snapshots, >self.capture_period<, to elapse before taking the next snapshot
                    Frames.append(self.capture())
                        # takes a snapshot and adds it to Frames
                    capture_time = time.time()
                        # updates the latest capture time
            self.reset()
                # resets the positions of the solenoids - I think this is unnecessary for solenoids
            print('Input ', i+1, 'complete, resetting reservoir')
            time.sleep(1)
                # Is there any need to wait 1s????
            Samples.append(self.seperate(Frames, background, show_filtered=show_filtered))
                # Adds the last example's num_frames snapshots to Samples

        Samples = np.array(Samples)
            # converts Samples into a numpy array

        if mode == 'train':
            self.train(Samples, outputs)
            if save:
                self.save_models()
        elif mode == 'test':
            answers, probabilities, results, combined_predictions, combined_accuracy = self.test(Samples, outputs)
            print('predictions: ', combined_predictions)
            return answers, probabilities, results, combined_predictions, combined_accuracy

class Maths:
    def __init__(self, matrix):
        self.m = matrix
            # Is this not useless?

    def AvMatrix(self, size):
        step_i, step_j = self.m.shape[0] // size[0], self.m.shape[1] // size[1]
            # // takes the quotient in a division and ignores the remainder (ie. applies the floor function to the division's result)
            # size is the desired number of outputs (ie. inputs to the SVM layer) from the Reservoir
                # eg. size=[20,20] means we compress the reservoir image into a 20x20 pixels image
        result = np.zeros((size[0], size[1]))
            # initialises a size[0]xsize[1] matrix of zeros
        for i in range(size[0]):
            # go through each row
            for j in range(size[1]):
                # go through each column
                result[i, j] = np.mean(self.m[i*step_i:i*step_i+step_i, j*step_j:j*step_j+step_j])
                    # replace the (i,j)^th entry in >result< with the average greyness in that area of the uncompressed image
        return result
            # return a size[0]xsize[1] compression of the image
